# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9867ef2ce9930b463bed97df1bb04ba91be3f1486e4001d0981c561ff4b6f19b276e5c8cb988d718a370cd15f97577c7fc46f7718667aca3f3e25fee1964bd9f

test:
  secret_key_base: 7f3874beedf1a67a5e7095e8ac947c6214e54a5582e18ecf3eab0a26cae54c98518a686f54d8ea0468b60ed307a19c212959f9cf6a4a8f9fd323a8516f64b463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
